name: "OpenMF Workflow Action"
description: "Automates CI/CD pipelines, code quality checks, and project issue management for OpenMF repositories."
author: "OpenMF Team"
branding:
  icon: "gear" # Choose an icon from GitHub's predefined list
  color: "blue" # Choose a predefined color from GitHub

inputs:
  repository_token:
    description: "GitHub token for accessing the repository."
    required: true
  branch:
    description: "The branch to run the action on."
    required: false
    default: "main"
  enable_ci:
    description: "Enable CI/CD pipeline automation."
    required: false
    default: "true"
  enable_code_quality:
    description: "Run code quality checks."
    required: false
    default: "true"

outputs:
  status:
    description: "The status of the action run."

runs:
  using: "node16"
  main: "index.js"

permissions:
  contents: "read"
  issues: "write"
  pull-requests: "write"

categories:
  - Automation
  - Continuous Integration
  - Code Quality

runs-on: ubuntu-latest
steps:
  - name: Checkout repository
    uses: actions/checkout@v3

  - name: Set up Node.js
    uses: actions/setup-node@v3
    with:
      node-version: "16"

  - name: Install dependencies
    run: npm install

  - name: Run CI/CD pipeline
    if: ${{ inputs.enable_ci == 'true' }}
    run: npm run ci

  - name: Run code quality checks
    if: ${{ inputs.enable_code_quality == 'true' }}
    run: npm run lint

  - name: Output status
    id: status
    run: echo "status=success" >> $GITHUB_ENV

